FROM ubuntu:latest
RUN apt-get update && \
    apt install net-tools -y \
    whois \
    curl \
    git \
    vim 

# Define variáveis de ambiente
# ENV MY_NAME Docker

# Executa um comando quando o container é iniciado
# CMD ["echo", "Hello, $MY_NAME!"]
